# Generated by Django 4.0.3 on 2022-03-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadsideCallout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=10)),
                ('location', models.TextField()),
                ('mechanic', models.CharField(max_length=25)),
                ('date', models.DateField()),
                ('rating', models.DecimalField(decimal_places=0, max_digits=1)),
                ('review', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(max_length=8),
        ),
    ]
