# Generated by Django 4.0.3 on 2022-03-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_roadsidecallout_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadsidecallout',
            name='mechanic',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='roadsidecallout',
            name='rating',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
        migrations.AlterField(
            model_name='roadsidecallout',
            name='review',
            field=models.TextField(default=''),
        ),
    ]
